frr version 8.4_git
frr defaults traditional
hostname leaf2
domainname localdomain
no ipv6 forwarding
!
vrf tenant-a
 vni 1000
exit-vrf
!
interface lo
 ip address 10.0.0.12/32
exit
!
interface br10
 ip address 192.168.10.12/24
exit
!
interface br20
 ip address 192.168.20.12/24
exit
!
router bgp 65012
 bgp router-id 10.0.0.12
 no bgp ebgp-requires-policy
 neighbor eth1 interface remote-as external
 neighbor eth2 interface remote-as external
 !
 address-family ipv4 unicast
  network 10.0.0.12/32
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor eth1 activate
  neighbor eth2 activate
  advertise-all-vni
  vni 20
   rd 10.0.0.12:20
   route-target import 65000:20
   route-target export 65000:20
  exit-vni
  vni 10
   rd 10.0.0.12:10
   route-target import 65000:10
   route-target export 65000:10
  exit-vni
  advertise-svi-ip
 exit-address-family
exit
!
router bgp 65012 vrf tenant-a
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.0.0.12:1000
  route-target import 65000:1000
  route-target export 65000:1000
 exit-address-family
exit
!
